### ISSUE TITLE
java.lang.NullPointerException        at com.google.sample.castcompanionlibrary.cast.BaseCastManager$1.doInBackground(BaseCastManager.java:854)

### ISSUE THREAD

**Issue by mntgoat** [googlecast/CastCompanionLibrary-android#143]
I've started receiving crash reports for this exception:

java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:299)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
       at java.util.concurrent.FutureTask.run(FutureTask.java:239)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:856)
Caused by: java.lang.NullPointerException
       at com.google.sample.castcompanionlibrary.cast.BaseCastManager$1.doInBackground(BaseCastManager.java:854)
       at com.google.sample.castcompanionlibrary.cast.BaseCastManager$1.doInBackground(BaseCastManager.java:840)
       at android.os.AsyncTask$2.call(AsyncTask.java:287)
       at java.util.concurrent.FutureTask.run(FutureTask.java:234)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:856)

Seems like this is the code causing it in the doInBackground method:

 if (mReconnectionTask.isCancelled()) {
                            return SUCCESS;
                        }

and I'm guessing mReconnectionTask is null but I'm not certain why because it gets set to null on onCancelled and onPostExecute but both of those should run after doInBackground. 

 protected void onCancelled() {
                    super.onCancelled();
                    mReconnectionTask = null;
                }

Anyways, I don't have a way to reproduce, just the crash reports. This is for version 1.12 of CCL.

**Comment by naddaf** [comment]
Try v1.13, hopefully that addressed the issue. If not, I would need more info.
