### ISSUE TITLE
java.lang.IllegalStateException: Not connected to a device

### ISSUE THREAD

**Issue by mntgoat** [googlecast/CastCompanionLibrary-android#144]
I have been getting reports (just a couple) of a crash because of a "java.lang.IllegalStateException: Not connected to a device" which seems to be happening at com.google.sample.castcompanionlibrary.cast.VideoCastManager.getVolume(VideoCastManager.java)

The code seems to be catching TransientNetworkDisconnectionException and NoConnectionException but not the IllegalStateException. This exception report was for version 1.12, and I have no way of reproducing it because it hasn't happened to me. 

java.lang.IllegalStateException: Not connected to a device
       at com.google.android.gms.internal.im.gb()
       at com.google.android.gms.internal.im.fZ()
       at com.google.android.gms.cast.Cast$CastApi$a.getVolume()
       at com.google.sample.castcompanionlibrary.cast.VideoCastManager.getVolume(VideoCastManager.java:615)
       at com.google.sample.castcompanionlibrary.cast.VideoCastManager.onRemoteMediaPlayerStatusUpdated(VideoCastManager.java:1563)
       at com.google.sample.castcompanionlibrary.cast.VideoCastManager.access$100(VideoCastManager.java:127)
       at com.google.sample.castcompanionlibrary.cast.VideoCastManager$9.onStatusUpdated(VideoCastManager.java:1344)
       at com.google.android.gms.cast.RemoteMediaPlayer.onStatusUpdated()
       at com.google.android.gms.cast.RemoteMediaPlayer.a()
       at com.google.android.gms.cast.RemoteMediaPlayer$1.onStatusUpdated()
       at com.google.android.gms.internal.it.a()
       at com.google.android.gms.internal.it.aD()
       at com.google.android.gms.cast.RemoteMediaPlayer.onMessageReceived()
       at com.google.android.gms.internal.im$c$4.run()
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5479)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by naddaf** [comment]
v1.14 should address this.
