### ISSUE TITLE
Unable to start media from VideoCastController: 'Failed to perform action'

### ISSUE THREAD

**Issue by aaearon** [googlecast/CastCompanionLibrary-android#146]
I have a local media player that utilizes Android's MediaPlayer and I have added a cast button to the media player activity's action bar. When a user starts the activity (playback starts immediately) and later goes to tap on the cast button, they are able to connect to the cast and the VideoCastController starts. When they tap the start button, they get a 'Failed to perform the action' toast and the below shows up in logcat. Let me know if this is more appropriate for the stackoverflow community.

````
01-05 11:37:25.328    3641-3641/com.iosharp.android.ssplayer E/ccl_VideoCastControlle﹕ [v1.14] Failed to toggle playback due to other issues
    java.lang.IllegalStateException: No current media session
            at com.google.android.gms.internal.it.fR(Unknown Source)
            at com.google.android.gms.internal.it.c(Unknown Source)
            at com.google.android.gms.cast.RemoteMediaPlayer$7.a(Unknown Source)
            at com.google.android.gms.cast.RemoteMediaPlayer$7.a(Unknown Source)
            at com.google.android.gms.common.api.BaseImplementation$a.b(Unknown Source)
            at com.google.android.gms.common.api.c.a(Unknown Source)
            at com.google.android.gms.common.api.c.b(Unknown Source)
            at com.google.android.gms.cast.RemoteMediaPlayer.play(Unknown Source)
            at com.google.sample.castcompanionlibrary.cast.VideoCastManager.play(VideoCastManager.java:1131)
            at com.google.sample.castcompanionlibrary.cast.VideoCastManager.play(VideoCastManager.java:1153)
            at com.google.sample.castcompanionlibrary.cast.player.VideoCastControllerFragment.togglePlayback(VideoCastControllerFragment.java:677)
            at com.google.sample.castcompanionlibrary.cast.player.VideoCastControllerFragment.onPlayPauseClicked(VideoCastControllerFragment.java:670)
            at com.google.sample.castcompanionlibrary.cast.player.VideoCastControllerActivity$1.onClick(VideoCastControllerActivity.java:188)
            at android.view.View.performClick(View.java:4475)
            at android.view.View$PerformClick.run(View.java:18796)
            at android.os.Handler.handleCallback(Handler.java:730)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5455)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1187)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
            at dalvik.system.NativeStart.main(Native Method)
````

**Comment by naddaf** [comment]
Are you serving your media through a web server in your app?

**Comment by aaearon** [comment]
No, all the media is remotely hosted (they are HLS streams and I have made sure that stream type is `STREAM_TYPE_LIVE`)

**Comment by naddaf** [comment]
Do you have your own custom receiver?

**Comment by aaearon** [comment]
No. I am using the styled media receiver without any css customizations. 

Von meinem iPhone gesendet

Am 05.01.2015 um 5:02 nachm. schrieb naddaf <notifications@github.com <mailto:notifications@github.com> >:

Do you have your own custom receiver?

**Comment by naddaf** [comment]
I suggest yo do the following first: grab the CastVideos reference app (android or iOS) and hardcode one of your stream URLs instead of the one that CastVideos uses and see if CastVideos can cast your stream or not. In addition,, you need to open a debug session to your chromecast and enable logging and then look at the console log to see what the receiver is throwing. Is CORS set up for your streams?

**Comment by aaearon** [comment]
The streams are functional and CORS is set up. The app kinda looks like this: A listview of 'channels' (streams) and if you tap on a channel, if the app is connected to a Chromecast, it will open the stream on the cast (does this successfully 100 percent of the time) otherwise will open the stream in the app's local media player, which has a cast button where from there you can open on the cast (this is the part where I get the `Failed to perform action`.

**Comment by naddaf** [comment]
Since I don't know how you are setting things up, won't be able to help you. As I suggested, take a look at the CastVideos-android app.
