### ISSUE TITLE
TransientNetworkDisconnectionException is crashing my app

### ISSUE THREAD

**Issue by jondwillis** [googlecast/CastCompanionLibrary-android#147]
I am seeing the following error in my production app using CCL 1.12 and 1.14, Google Play Services 6.5.87. It happens seemingly randomly, sometimes going hours of casting without happening, other times it can happen almost immediately.

    01-06 11:08:21.316  13337-13337/tv.pluto.android E/ccl_VideoCastManager﹕ [v1.14] Failed to get volume
    com.google.sample.castcompanionlibrary.cast.exceptions.TransientNetworkDisconnectionException
            at com.google.sample.castcompanionlibrary.cast.BaseCastManager.checkConnectivity(BaseCastManager.java:1144)
            at com.google.sample.castcompanionlibrary.cast.VideoCastManager.getVolume(VideoCastManager.java:610)
            at com.google.sample.castcompanionlibrary.cast.VideoCastManager.onVolumeChanged(VideoCastManager.java:872)
            at com.google.sample.castcompanionlibrary.cast.VideoCastManager.access$700(VideoCastManager.java:128)
            at com.google.sample.castcompanionlibrary.cast.VideoCastManager$CastListener.onVolumeChanged(VideoCastManager.java:1988)
            at com.google.android.gms.internal.im.a(Unknown Source)
            at com.google.android.gms.internal.im.a(Unknown Source)
            at com.google.android.gms.internal.im$c$2.run(Unknown Source)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

Is there any way to handle this exception that I am missing?

**Comment by naddaf** [comment]
Are you sure it is causing a crash? Here is the relevant piece of code:

    private void onVolumeChanged() {
        LOGD(TAG, "onVolumeChanged() reached");
        double volume;
        try {
            volume = getVolume();
            boolean isMute = isMute();
            for (IVideoCastConsumer consumer : mVideoConsumers) {
                consumer.onVolumeChanged(volume, isMute);
            }
        } catch (TransientNetworkDisconnectionException | NoConnectionException e) {
            LOGE(TAG, "Failed to get volume", e);
        }
    }

and as you can see, that exception is caught and logged but that is all, it is not bubbled up.

**Comment by jondwillis** [comment]
Ah, you're right. I have some questions:
1) What exactly is a TransientNetworkDisconnectionException? 
2) Where can I handle TransientNetworkDisconnectionException and what is a reasonable approach to take if I want to try to reconnect?

**Comment by naddaf** [comment]
That exception is an indication that the connectivity is in suspended state. When the Cast SDK loses its connectivity, it will transition the connectivity state to "suspended" and then tries to reconnect and it either succeeds (and state changes to "connected") or it fails and state changes to "connection failed". 
From developer's point of view, you shouldn't take any particular action, CCL has a callback onConnectionSuspended() that you can listen to and is called when this suspension happens and you may decide to disable certain UI elements at that point, and if SDK cannot reestablish connectivity, the state goes to "connection failed" and you will obviously receive a callback on onConnectionFailed(ConnectionResult); ConnectionResult includes the reason for failure.

**Comment by softvision-florin-tite** [comment]
It seems that the root cause of this crash is still there, and is generally caused by "BaseCastManager.checkConnectivity()" method that throws the connection exceptions in any context form which is called, and in most of the cases those exceptions are not caught at all, and are very hard to catch outside Cast SDK. (the "onVolumeChanged()" is on the short list of happy cases when we have a friendly handling inside Cast SDK).

In many other cases, these exceptions will either bubbled up or cause other cascade issues and crash the current cast activity or even the app. 

In my case: 
- when casting a supported ".mp4" file  (20 MB) from Android app to Chromecast, the crash occurs at the end of the video, just wait for video to end by itself.  Happens all the time on any Android >= 4.0, including M Preview3, using "targetSdkVersion" 22 or 23 for builds:

- First I see this in logs (not the crash source since is caught in Cast SDK):    
```
09-09 12:28:00.080  23144-23144/? E/GmsClient? Calling connect() while still connected, missing disconnect() for com.google.android.gms.cast.service.BIND_CAST_DEVICE_CONTROLLER_SERVICE
09-09 12:28:00.540  23144-23144/? E/ccl_VideoCastManager? [v2.2] Failed to get volume
    com.google.android.libraries.cast.companionlibrary.cast.exceptions.TransientNetworkDisconnectionException
            at com.google.android.libraries.cast.companionlibrary.cast.BaseCastManager.checkConnectivity(BaseCastManager.java:1053)
            at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.getVolume(VideoCastManager.java:636)
            at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.onVolumeChanged(VideoCastManager.java:861)
            at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.access$1100(VideoCastManager.java:138)
            at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager$CastListener.onVolumeChanged(VideoCastManager.java:2486)
            at com.google.android.gms.cast.internal.zze.zza(Unknown Source)
            at com.google.android.gms.cast.internal.zze.zza(Unknown Source)
            at com.google.android.gms.cast.internal.zze$zzb$2.run(Unknown Source)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5602)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
            at dalvik.system.NativeStart.main(Native Method)
```

- Then I see this - seems to be the crash root: 
```
 java.lang.NullPointerException
            at com.google.android.libraries.cast.companionlibrary.cast.player.VideoCastControllerFragment.updatePlayerStatus(VideoCastControllerFragment.java:470)
            at com.google.android.libraries.cast.companionlibrary.cast.player.VideoCastControllerFragment.access$1000(VideoCastControllerFragment.java:75)
            at com.google.android.libraries.cast.companionlibrary.cast.player.VideoCastControllerFragment$MyCastConsumer.onRemoteMediaPlayerStatusUpdated(VideoCastControllerFragment.java:260)
            at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.onRemoteMediaPlayerStatusUpdated(VideoCastManager.java:2106)
            at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.access$200(VideoCastManager.java:138)
            at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager$22.onStatusUpdated(VideoCastManager.java:1793)
            at com.google.android.gms.cast.RemoteMediaPlayer.onStatusUpdated(Unknown Source)
            at com.google.android.gms.cast.RemoteMediaPlayer.zza(Unknown Source)
            at com.google.android.gms.cast.RemoteMediaPlayer$1.onStatusUpdated(Unknown Source)
            at com.google.android.gms.cast.internal.zzm.zza(Unknown Source)
            at com.google.android.gms.cast.internal.zzm.zzbB(Unknown Source)
            at com.google.android.gms.cast.RemoteMediaPlayer.onMessageReceived(Unknown Source)
            at com.google.android.gms.cast.internal.zze$zzb$4.run(Unknown Source)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5602)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
            at dalvik.system.NativeStart.main(Native Method)
```       

My Gradle build configs used for testing are:

For target 22:
```
minSdkVersion 14
targetSdkVersion 22 

    compile 'com.android.support:support-v4:22.2.1'
    compile 'com.android.support:mediarouter-v7:22.2.1'
    compile 'com.android.support:appcompat-v7:22.2.1'
    compile 'com.google.android.gms:play-services-base:7.5.0'
    compile 'com.google.android.gms:play-services-analytics:7.5.0'
    compile 'com.google.android.gms:play-services-cast:7.5.0'
```

For target 23:
```
minSdkVersion 14
targetSdkVersion 23 
    compile 'com.android.support:support-v4:23.0.0'
    compile 'com.android.support:mediarouter-v7:23.0.0'
    compile 'com.android.support:appcompat-v7:23.0.0'
    compile 'com.google.android.gms:play-services-base:7.8.0'
    compile 'com.google.android.gms:play-services-analytics:7.8.0'
    compile 'com.google.android.gms:play-services-cast:7.8.0'     
```

Note:
It would be very helpful to have the possibility to managed/overwrite  the behavior of "BaseCastManager.checkConnectivity()"  method by extending the CastManager(specially for VideoCastManager) . Currently this method is "public final".

I'm asking this because the above method is used in various scenarios/places inside VideoCastManager.class, and causes unwanted crashes.   
Or at least catch the exceptions it throws inside Cast SDK, where the method call is used, and handle the cast states in a friendly way, instead of having the exceptions bubble up for any involved cast states.

Current behavior is also causing a lot of troubles if you try to add/integrate, in parallel, custom cast support for other cast devices.
