### ISSUE TITLE
com.google.sample.castcompanionlibrary.cast.exceptions.NoConnectionException:

### ISSUE THREAD

**Issue by mntgoat** [googlecast/CastCompanionLibrary-android#159]
Why do I get NoConnectionException if my code looks like this:

```
if (castManager.isConnected()) {
         return (int) (castManager.getVolume() * 100);
}
```

It is the most reported exception I have on crashlytics. I am catching so the app isn't crashing but still seems odd. Surely the user ins't getting disconnected between the check of isConnected and the getting of the volume?

```
com.google.sample.castcompanionlibrary.cast.exceptions.NoConnectionException: getDeviceVolume()
       at com.google.sample.castcompanionlibrary.cast.BaseCastManager.getDeviceVolume(BaseCastManager.java:607)
       at com.google.sample.castcompanionlibrary.cast.VideoCastManager.getVolume(VideoCastManager.java:615)
```

**Comment by naddaf** [comment]
Is it during initial connection or at the moment they are dropping teh connection or what exactly?

**Comment by mntgoat** [comment]
I have my own video playback control activity, it is happening on the onCreate method of that activity which means it played a video successfully, or the app just connected and found that one was playing. or they clicked on the notification, or the mini controller. I don't ever auto start that activity unless I get a "onApplicationStatusChanged" with "Now Casting".
