### ISSUE TITLE
java.lang.RuntimeException  at com.google.sample.castcompanionlibrary.cast.VideoCastManager.(VideoCastManager.java:243)

### ISSUE THREAD

**Issue by mntgoat** [googlecast/CastCompanionLibrary-android#160]
Odd exception affecting some users. It is happening on this line:

```
        mAudioManager = (AudioManager) mContext.getSystemService(Context.AUDIO_SERVICE);
```

I'm guessing it is a rom bug but I was wondering if there is something we can do so the app doesn't crash for those users as it isn't a critical part of the VideoCastManager. For now I'm just going to put a try catch around that line on my copy of VideoCastManager. 

```
java.lang.RuntimeException: Unable to create service MyService: android.content.res.Resources$NotFoundException: Resource ID #0x111000a
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2376)
       at android.app.ActivityThread.access$1600(ActivityThread.java:133)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4777)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:998)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:765)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x111000a
       at android.content.res.Resources.getValue(Resources.java:1884)
       at android.content.res.Resources.getBoolean(Resources.java:1666)
       at android.media.AudioManager.(AudioManager.java:480)
       at android.app.ContextImpl$6.createService(ContextImpl.java:317)
       at android.app.ContextImpl$ServiceFetcher.getService(ContextImpl.java:235)
       at android.app.ContextImpl.getSystemService(ContextImpl.java:1369)
       at android.content.ContextWrapper.getSystemService(ContextWrapper.java:423)
       at com.google.sample.castcompanionlibrary.cast.VideoCastManager.(VideoCastManager.java:243)
       at com.google.sample.castcompanionlibrary.cast.VideoCastManager.initialize(VideoCastManager.java:195)
```

**Comment by naddaf** [comment]
The exception is not really thrown because of a missing resource on the CCL part; what type of device is that? All line 243 of VideoCastManager is doing is getting AudioService from system so something on that device is not standard (a rooted device with a special ROM, etc). There is nothing that CCL needs to do here.
