### ISSUE TITLE
java.lang.RuntimeException: Unable to start receiver com.google.android.libraries.cast.companionlibrary.remotecontrol.VideoIntentReceiver

### ISSUE THREAD

**Issue by fanno** [googlecast/CastCompanionLibrary-android#163]
Hello once again, (happy easter)

```java
java.lang.RuntimeException: Unable to start receiver com.google.android.libraries.cast.companionlibrary.remotecontrol.VideoIntentReceiver: java.lang.IllegalStateException: No VideoCastManager instance was found, did you forget to initialize it?
at android.app.ActivityThread.handleReceiver(ActivityThread.java:2642)
at android.app.ActivityThread.access$1700(ActivityThread.java:149)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1401)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:211)
at android.app.ActivityThread.main(ActivityThread.java:5321)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
Caused by: java.lang.IllegalStateException: No VideoCastManager instance was found, did you forget to initialize it?
at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.getInstance(VideoCastManager.java:239)
at com.google.android.libraries.cast.companionlibrary.remotecontrol.VideoIntentReceiver.onReceive(VideoIntentReceiver.java:44)
at android.app.ActivityThread.handleReceiver(ActivityThread.java:2635)
... 9 more
```

I have a good amount of this error. since i switch to libery, i do not know if this is some new (so far i have not recreate it my self)

i init the VideoCastManager inside my main activity.

```java
@Override
	protected void onCreate(Bundle savedInstanceState) {
mChromecast = Chromecast.getInstance(); // initiate happens in here.
..
}
```
should i move the initiate Application class ? eg:
```java
public class GlobalApplication extends Application {
@Override
	public void onCreate() {
		...
		Chromecast.getInstance();
	}
}
```

Or ? is there a 3rd option i should be using ?

**Comment by naddaf** [comment]
You are not initializing the cast manager prior to using that; take a look at the CastVideos-android app, in the CastApplication class there (https://github.com/googlecast/CastVideos-android/blob/master/src/com/google/sample/cast/refplayer/CastApplication.java#L42) to see how you can initialize it; once initialized, then you can access it by calling VideoCastManager.getInstance().
