### ISSUE TITLE
NullPointerException in FetchBitmapTask.scaleBitmap (CCL 1.14)

### ISSUE THREAD

**Issue by apkelly** [googlecast/CastCompanionLibrary-android#165]
Hi,

I'm using v1.14 of the CCL in my app, and I've had 80 crashes for 1 user reported in Crashlytics, the stack trace is below.

The device details are: Samsung GT-I9100 running Android 4.1.2

I believe the image that the CCL is trying to download is this one.

https://lh5.ggpht.com/cRNwHjXej6ziuVUuX65kNW0Zn4dEAYFzT_eLS5uecH772llwJjD4Sd41eyaUS_vtlKRY=w300-rw

Thanks,

Andy.

java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:299)
       at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
       at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
       at java.util.concurrent.FutureTask.run(FutureTask.java:137)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
       at java.lang.Thread.run(Thread.java:856)
Caused by: java.lang.NullPointerException
       at com.google.sample.castcompanionlibrary.utils.FetchBitmapTask.scaleBitmap(FetchBitmapTask.java:117)
       at com.google.sample.castcompanionlibrary.utils.FetchBitmapTask.doInBackground(FetchBitmapTask.java:82)
       at com.google.sample.castcompanionlibrary.utils.FetchBitmapTask.doInBackground(FetchBitmapTask.java:38)
       at android.os.AsyncTask$2.call(AsyncTask.java:287)
       at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
       at java.util.concurrent.FutureTask.run(FutureTask.java:137)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
       at java.lang.Thread.run(Thread.java:856)

**Comment by naddaf** [comment]
v1.14 is no longer in active development, I suggest you upgrade to 2.0 and see if the issue persists.

**Comment by apkelly** [comment]
The same bit of code exists in v2.0, there is still no null check in the scaleBitmap method.

    private Bitmap scaleBitmap(Bitmap bitmap) {
        int width = bitmap.getWidth();
        int height = bitmap.getHeight();

**Comment by naddaf** [comment]
why is bitmap null?

**Comment by naddaf** [comment]
Regarding your second question, I was waiting to iron out small issues that people would come across and fix those before tagging the trunk. For example this NPE you are seeing, I can fix that easily but I'd like to understand whey a bitmap is null first.

**Comment by apkelly** [comment]
I included a link to the URL which I believe is being downloaded by the AsyncTask, it looks like the Bitmap.decodeStream method is returning null for a stream that has a status HTTP_OK.

**Comment by naddaf** [comment]
And can you reproduce it? Is it just that one device/model?

**Comment by apkelly** [comment]
I don't have a large user base for my app at the moment and Chromecast support was only a recent addition. I don't see the error when casting from my personal Nexus 5 and Crashlytics only has 1 user being affected by this crash.
