### ISSUE TITLE
NullPointerException in VideoIntentReceiver.onReceive (CCL 1.14)

### ISSUE THREAD

**Issue by apkelly** [googlecast/CastCompanionLibrary-android#166]
Hi,

I get the following crash reported in Crashlytics, stack trace included below.

The details of the device that reported this crash are Samsung?? GI-I9500_TMMARS with Android v4.1.1

Thanks,

Andy.

java.lang.RuntimeException: Unable to start receiver com.google.sample.castcompanionlibrary.remotecontrol.VideoIntentReceiver: java.lang.NullPointerException
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2237)
       at android.app.ActivityThread.access$1500(ActivityThread.java:131)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1272)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4754)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.NullPointerException
       at com.google.sample.castcompanionlibrary.remotecontrol.VideoIntentReceiver.onReceive(VideoIntentReceiver.java:81)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2230)
       at android.app.ActivityThread.access$1500(ActivityThread.java:131)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1272)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4754)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by naddaf** [comment]
v1.14 is no longer in active development, I suggest you upgrade to 2.0 and see if the issue persists.
