### ISSUE TITLE
VideoCastManager.setTextTrackStyle cause error

### ISSUE THREAD

**Issue by iceteahh** [googlecast/CastCompanionLibrary-android#182]
I face with this error when im trying to change style of caption:

```
06-12 14:35:47.552    5275-5275/com.mhdviets.app.android W/System.err﹕ java.lang.IllegalStateException: No current media session
06-12 14:35:47.552    5275-5275/com.mhdviets.app.android W/System.err﹕ at com.google.android.gms.cast.internal.zzm.zzls(Unknown Source)
06-12 14:35:47.552    5275-5275/com.mhdviets.app.android W/System.err﹕ at com.google.android.gms.cast.internal.zzm.zza(Unknown Source)
06-12 14:35:47.552    5275-5275/com.mhdviets.app.android W/System.err﹕ at com.google.android.gms.cast.RemoteMediaPlayer$3.zza(Unknown Source)
06-12 14:35:47.552    5275-5275/com.mhdviets.app.android W/System.err﹕ at com.google.android.gms.cast.RemoteMediaPlayer$3.zza(Unknown Source)
06-12 14:35:47.552    5275-5275/com.mhdviets.app.android W/System.err﹕ at com.google.android.gms.common.api.zza$zza.zzb(Unknown Source)
06-12 14:35:47.552    5275-5275/com.mhdviets.app.android W/System.err﹕ at com.google.android.gms.common.api.zzd.zza(Unknown Source)
06-12 14:35:47.552    5275-5275/com.mhdviets.app.android W/System.err﹕ at com.google.android.gms.common.api.zzd.zzb(Unknown Source)
06-12 14:35:47.552    5275-5275/com.mhdviets.app.android W/System.err﹕ at com.google.android.gms.common.api.zzg.zzb(Unknown Source)
06-12 14:35:47.552    5275-5275/com.mhdviets.app.android W/System.err﹕ at com.google.android.gms.cast.RemoteMediaPlayer.setTextTrackStyle(Unknown Source)
06-12 14:35:47.552    5275-5275/com.mhdviets.app.android W/System.err﹕ at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.setTextTrackStyle(VideoCastManager.java:2635)
06-12 14:35:47.552    5275-5275/com.mhdviets.app.android W/System.err﹕ at com.mhdviets.app.android.fragments.CasterFragment.loadRemoteMedia(CasterFragment.java:279)
06-12 14:35:47.562    5275-5275/com.mhdviets.app.android W/System.err﹕ at com.mhdviets.app.android.fragments.CasterFragment$1.onApplicationConnected(CasterFragment.java:147)
06-12 14:35:47.562    5275-5275/com.mhdviets.app.android W/System.err﹕ at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.onApplicationConnected(VideoCastManager.java:915)
06-12 14:35:47.562    5275-5275/com.mhdviets.app.android W/System.err﹕ at com.google.android.libraries.cast.companionlibrary.cast.BaseCastManager$3.onResult(BaseCastManager.java:981)
06-12 14:35:47.562    5275-5275/com.mhdviets.app.android W/System.err﹕ at com.google.android.libraries.cast.companionlibrary.cast.BaseCastManager$3.onResult(BaseCastManager.java:975)
06-12 14:35:47.562    5275-5275/com.mhdviets.app.android W/System.err﹕ at com.google.android.gms.common.api.AbstractPendingResult$CallbackHandler.deliverResultCallback(Unknown Source)
06-12 14:35:47.562    5275-5275/com.mhdviets.app.android W/System.err﹕ at com.google.android.gms.common.api.AbstractPendingResult$CallbackHandler.handleMessage(Unknown Source)
06-12 14:35:47.562    5275-5275/com.mhdviets.app.android W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:102)
06-12 14:35:47.562    5275-5275/com.mhdviets.app.android W/System.err﹕ at android.os.Looper.loop(Looper.java:145)
06-12 14:35:47.562    5275-5275/com.mhdviets.app.android W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:6141)
06-12 14:35:47.562    5275-5275/com.mhdviets.app.android W/System.err﹕ at java.lang.reflect.Method.invoke(Native Method)
06-12 14:35:47.562    5275-5275/com.mhdviets.app.android W/System.err﹕ at java.lang.reflect.Method.invoke(Method.java:372)
06-12 14:35:47.562    5275-5275/com.mhdviets.app.android W/System.err﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
06-12 14:35:47.562    5275-5275/com.mhdviets.app.android W/System.err﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```
I have called castManager.setTextTrackStyle(textTrackStyle); right after castManager.startVideoCastControllerActivity(activity, activity.mediaInfo, position, autoPlay);

**Comment by naddaf** [comment]
It seems you are doing it too early before the media session starts; you might want to wait for the playback to start before doing that
