### ISSUE TITLE
java.lang.NoClassDefFoundError: android.support.v7.mediarouter.R$string

### ISSUE THREAD

**Issue by iceteahh** [googlecast/CastCompanionLibrary-android#201]
My application using your library version 2.3.1. When it run on Samsung galaxy s6 it is OK. But when i run it on Nexus 7 2017, Samsung Note 2 it crashed, logcat:
```
08-20 15:12:15.929    6866-6866/com.flix.apps.android E/GooglePlayServicesUtil﹕ The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.
08-20 15:12:15.959    6866-6866/com.flix.apps.android E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.flix.apps.android, PID: 6866
    java.lang.NoClassDefFoundError: android.support.v7.mediarouter.R$string
            at android.support.v7.media.SystemMediaRouteProvider$JellybeanImpl.<init>(SystemMediaRouteProvider.java:256)
            at android.support.v7.media.SystemMediaRouteProvider$JellybeanMr1Impl.<init>(SystemMediaRouteProvider.java:716)
            at android.support.v7.media.SystemMediaRouteProvider$JellybeanMr2Impl.<init>(SystemMediaRouteProvider.java:788)
            at android.support.v7.media.SystemMediaRouteProvider.obtain(SystemMediaRouteProvider.java:53)
            at android.support.v7.media.MediaRouter$GlobalMediaRouter.<init>(MediaRouter.java:1652)
            at android.support.v7.media.MediaRouter.getInstance(MediaRouter.java:246)
            at com.google.android.libraries.cast.companionlibrary.cast.BaseCastManager.<init>(BaseCastManager.java:189)
            at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.<init>(VideoCastManager.java:224)
            at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.initialize(VideoCastManager.java:250)
            at com.flix.apps.android.FlixApplication.onCreate(FlixApplication.java:53)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4328)
            at android.app.ActivityThread.access$1500(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)
```
`at com.flix.apps.android.FlixApplication.onCreate(FlixApplication.java:53)` is:
```
VideoCastManager.
                initialize(this, CastMediaControlIntent.DEFAULT_MEDIA_RECEIVER_APPLICATION_ID, null, null)
                .enableFeatures(VideoCastManager.FEATURE_NOTIFICATION |
                        VideoCastManager.FEATURE_LOCKSCREEN |
                        VideoCastManager.FEATURE_WIFI_RECONNECT |
                        VideoCastManager.FEATURE_CAPTIONS_PREFERENCE |
                        VideoCastManager.FEATURE_DEBUGGING);
```

I followed your document and used `MediaRouteButton` like this:

```
<android.support.v7.app.MediaRouteButton
android:id="@+id/media_route_button"
android:layout_width="wrap_content"
android:layout_height="wrap_content"
android:mediaRouteTypes="user" />
```

**Comment by iceteahh** [comment]
Sorry that was my mistake, i have used `multiDexEnabled = true` in my build config. Please close it.
