### ISSUE TITLE
Add ProGuard configuration

### ISSUE THREAD

**Issue by Nimrodda** [googlecast/CastCompanionLibrary-android#206]
Could you please add the required configuration for ProGuard?

I tried
```
#Cast Companion
-keep class com.google.android.libraries.** { *; }
```

but apparently it's not enough because the app crashes with the following exception:
```
 java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.app.ao.a(android.support.v7.c.o)' on a null object reference
            at com.google.android.libraries.cast.companionlibrary.cast.BaseCastManager.addMediaRouterButton(Unknown Source)
            at com.example.CastActivity.onCreateOptionsMenu(Unknown Source)
            at android.app.Activity.onCreatePanelMenu(Activity.java:2823)
            at android.support.v4.app.u.onCreatePanelMenu(Unknown Source)
            at android.support.v7.internal.view.k.onCreatePanelMenu(Unknown Source)
            at android.support.v7.app.aa.onCreatePanelMenu(Unknown Source)
            at android.support.v7.app.AppCompatDelegateImplV7.b(Unknown Source)
            at android.support.v7.app.AppCompatDelegateImplV7.e(Unknown Source)
            at android.support.v7.app.AppCompatDelegateImplV7.a(Unknown Source)
            at android.support.v7.app.ae.run(Unknown Source)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

I managed to solve it by adding
```
-keep class android.support.v7.** { *; }
```
but shouldn't that be automatically added? At least that what I understood from the support libraries documentation.

**Comment by naddaf** [comment]
Unfortunately, I don't have any specific knowledge of ProGaurd config files ...

**Comment by Nimrodda** [comment]
Yes, it is resolved. Though it's strange because I was using android.support.v7 library before integrating Cast Companion and I didn't need to have that line.

**Comment by naddaf** [comment]
Closing the issue,
