### ISSUE TITLE
NPE in library

### ISSUE THREAD

**Issue by branislav-zlatkovic** [googlecast/CastCompanionLibrary-android#252]
got the following NPE:

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.support.v4.media.MediaMetadataCompat.getMediaMetadata()' on a null object reference
                                                                     at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplApi21.setMetadata(MediaSessionCompat.java:1869)
                                                                     at android.support.v4.media.session.MediaSessionCompat.setMetadata(MediaSessionCompat.java:331)
                                                                     at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.clearMediaSession(VideoCastManager.java:2461)
                                                                     at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.onDisconnected(VideoCastManager.java:2581)
                                                                     at com.google.android.libraries.cast.companionlibrary.cast.BaseCastManager.disconnectDevice(BaseCastManager.java:324)
                                                                     at com.google.android.libraries.cast.companionlibrary.cast.BaseCastManager.onDeviceSelected(BaseCastManager.java:227)
                                                                     at com.google.android.libraries.cast.companionlibrary.cast.CastMediaRouterCallback.onRouteUnselected(CastMediaRouterCallback.java:64)
                                                                     at android.support.v7.media.MediaRouter$GlobalMediaRouter$CallbackHandler.invokeCallback(MediaRouter.java:2476)
                                                                     at android.support.v7.media.MediaRouter$GlobalMediaRouter$CallbackHandler.handleMessage(MediaRouter.java:2423)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:211)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5389)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)

it happens when tap on 'stop casting' from the cast action item while video is still playing on cast receiver.

**Comment by naddaf** [comment]
I am not seeing that, can you reproduce that with CastVideos (first enable
logging in CCL) and if so, show the stack trace here?

**Comment by branislav-zlatkovic** [comment]
Not able to reproduce it with CastVideos.
I'm trying to make one activity that should be both local player and remote play controller (similar to YouTube, so I'm not using the default VideoCastControllerActivity). I've integrated the lib according to the pdf and the CastVideos example, the only significant difference (ATM) being:
mCastManager.loadMedia(mSelectedMedia, autoPlay, position);
instead of
mCastManager.startVideoCastControllerActivity(this, mSelectedMedia, position, autoPlay);
in method loadRemoteMedia(). This call comes from onApplicationConnected() in setupCastListener()
 where I also skip finis() the current activity as LocalPlayerActivity does. This could explain why I'm not able to reproduce this with CastVideos, because if I leave my player activity and stop casting, this NPE won't happen at all.

**Comment by naddaf** [comment]
What versions of MediaRouter support lib, appcompat lib, play services and ccl are you using?

**Comment by branislav-zlatkovic** [comment]
mediarouter and appcompat are 22.2.1
play services 7.8.0 and ccl 2.6.1

just to add up, looking at the android.support.v4.media.session.MediaSessionCompat$MediaSessionImplApi21.setMetadata(MediaSessionCompat.java:1869) where the crash happens, the method looks like this:
@Override
        public void setMetadata(MediaMetadataCompat metadata) {
            MediaSessionCompatApi21.setMetadata(mSessionObj, metadata.getMediaMetadata());
        }

The metadata argument to this method is null, as it is set in VideoCastManager#clearMediaSession line 2461, leading to metadata.getMediaMetadata() throwing a NPE

**Comment by naddaf** [comment]
You need to update your support libraries to the latest (23.1.1) and also it is good to update your play services as well. In the recent support lib, you have:

        public void setMetadata(MediaMetadataCompat metadata) {
            MediaSessionCompatApi21.setMetadata(mSessionObj,
                    metadata == null ? null : metadata.getMediaMetadata());
        }

which would fix this bug.

**Comment by branislav-zlatkovic** [comment]
the description on the homepage says the dependencies are 22 and above, so is there any other way to keep using version 22 libs and avoid this bug, as the bringup to the latest libs is not possible for the project at this moment?

**Comment by naddaf** [comment]
You should seriously consider moving to v23; it has a large number of fixes
over v22. Meanwhile, comment out the line that does sets the metadata to
null.

**Comment by branislav-zlatkovic** [comment]
Alright, thanks a bunch for the help!
