### ISSUE TITLE
when video play completes CCL crashes on null pointer (v2.6.1)

### ISSUE THREAD

**Issue by Matthew-C** [googlecast/CastCompanionLibrary-android#254]
Attached please see the call stack:
FATAL EXCEPTION: main
                                                                                       Process: com.ooyala.sample.ChromecastSampleApp, PID: 10154
                                                                                       java.lang.NullPointerException: Attempt to invoke virtual method 'int android.media.MediaMetadata.size()' on a null object reference
                                                                                           at android.os.Parcel.readException(Parcel.java:1546)
                                                                                           at android.os.Parcel.readException(Parcel.java:1493)
                                                                                           at android.media.session.ISession$Stub$Proxy.setMetadata(ISession.java:398)
                                                                                           at android.media.session.MediaSession.setMetadata(MediaSession.java:411)
                                                                                           at android.support.v4.media.session.MediaSessionCompatApi21.setMetadata(MediaSessionCompatApi21.java:104)
                                                                                           at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplApi21.setMetadata(MediaSessionCompat.java:2022)
                                                                                           at android.support.v4.media.session.MediaSessionCompat.setMetadata(MediaSessionCompat.java:380)
                                                                                           at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.clearMediaSession(VideoCastManager.java:2461)
                                                                                           at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.onRemoteMediaPlayerStatusUpdated(VideoCastManager.java:2074)
                                                                                           at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.access$200(VideoCastManager.java:140)
                                                                                           at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager$22.onStatusUpdated(VideoCastManager.java:1795)
                                                                                           at com.google.android.gms.cast.RemoteMediaPlayer.onStatusUpdated(Unknown Source)
                                                                                           at com.google.android.gms.cast.RemoteMediaPlayer.zza(Unknown Source)
                                                                                           at com.google.android.gms.cast.RemoteMediaPlayer$1.onStatusUpdated(Unknown Source)
                                                                                           at com.google.android.gms.cast.internal.zzm.zza(Unknown Source)
                                                                                           at com.google.android.gms.cast.internal.zzm.zzbZ(Unknown Source)
                                                                                           at com.google.android.gms.cast.RemoteMediaPlayer.onMessageReceived(Unknown Source)
                                                                                           at com.google.android.gms.cast.internal.zze$zzb$4.run(Unknown Source)
                                                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                           at android.os.Looper.loop(Looper.java:135)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:5221)
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by naddaf** [comment]
Make sure you are using the latest version of MediaRoute support lib, see #252

**Comment by Matthew-C** [comment]
I'm using whatever dependencies specified in CCL 2.6.1 
dependencies {
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:mediarouter-v7:23.1.1'
    compile 'com.google.android.gms:play-services-cast:8.3.0'
}

It seems the crash only happens on Android 5.0 but not on 4.4/5.1/6.0. Where can I check the source code of the setMetaData method I'm using?

**Comment by naddaf** [comment]
I still believe you are using an older version of mediarouter library, brought in by possibly other dependencies; you can do a "gradle dependencies" to see the dependencies. I just ran CastVideos-android in an emulator with Api 21 and didn't see any issue. The reason I believe you are running an older version is that the source from the stack trace doesn't match with the latest version (see, for example https://github.com/android/platform_frameworks_support/tree/master/v4/java/android/support/v4/media/session). In fact, there is no MediaSessionCompatApi21.java any more; that is now an inner-class in MediaSessionCompat. I also suggest running CastVideos-android if you are not doing so already.

**Comment by Matthew-C** [comment]
@naddaf thank you for you response.

I listed dependencies:
+--- project :CastCompanionLibrary
|    +--- com.android.support:appcompat-v7:23.1.1
|    |    \--- com.android.support:support-v4:23.1.1
|    |         \--- com.android.support:support-annotations:23.1.1
|    +--- com.android.support:mediarouter-v7:23.1.1
|    |    +--- com.android.support:appcompat-v7:23.1.1 (*)
|    |    \--- com.android.support:palette-v7:23.1.1
|    |         \--- com.android.support:support-v4:23.1.1 (*)
|    \--- com.google.android.gms:play-services-cast:8.3.0
|         +--- com.google.android.gms:play-services-base:8.3.0
|         |    \--- com.google.android.gms:play-services-basement:8.3.0
|         |         \--- com.android.support:support-v4:22.2.0 -> 23.1.1 (*)
|         \--- com.android.support:mediarouter-v7:22.2.0 -> 23.1.1 (*)
It seems play-services-cast 8.3.0 still uses the old version of media router.

**Comment by naddaf** [comment]
The lines there show that Play Services was compiled with an older version but since you have provided a newer version, that dependency is being fulfilled with the newer version; that is what the 
" -> " means:
com.android.support:mediarouter-v7:22.2.0 -> 23.1.1
Please check the dependencies at the level of your project not just CCL.
