### ISSUE TITLE
java.lang.NullPointerExceptio at VideoCastManager.reattachDataChannel

### ISSUE THREAD

**Issue by mntgoat** [googlecast/CastCompanionLibrary-android#255]
I got this exception over crashlytics but I have no idea how to reproduce it. 

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.common.api.Api$zzb com.google.android.gms.common.api.GoogleApiClient.zza(com.google.android.gms.common.api.Api$zzc)' on a null object reference
       at com.google.android.gms.cast.Cast$CastApi$zza.setMessageReceivedCallbacks(Unknown Source)
       at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.reattachDataChannel(VideoCastManager.java:1958)
       at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.onConnectivityRecovered(VideoCastManager.java:932)
       at com.google.android.libraries.cast.companionlibrary.cast.BaseCastManager.onConnected(BaseCastManager.java:917)
       at com.google.android.gms.common.internal.zzk.zzk(Unknown Source)
       at com.google.android.gms.internal.zzmg.zzi(Unknown Source)
       at com.google.android.gms.internal.zzme.zzpi(Unknown Source)
       at com.google.android.gms.internal.zzme.onConnected(Unknown Source)
       at com.google.android.gms.internal.zzmi.onConnected(Unknown Source)
       at com.google.android.gms.internal.zzlz.onConnected(Unknown Source)
       at com.google.android.gms.common.internal.zzj$zzg.zzqv(Unknown Source)
       at com.google.android.gms.common.internal.zzj$zza.zzc(Unknown Source)
       at com.google.android.gms.common.internal.zzj$zza.zzv(Unknown Source)
       at com.google.android.gms.common.internal.zzj$zzc.zzqx(Unknown Source)
       at com.google.android.gms.common.internal.zzj$zzb.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5292)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

**Comment by naddaf** [comment]
It seems to be an older version of the library since line 1958 of
VideoCastManager is pointing to a blank line.  Can you point me to the
correct line in that class where the error is happening? What CCL version
is that?

**Comment by mntgoat** [comment]
It is on this method:
```
private void reattachDataChannel() {
        if (!TextUtils.isEmpty(mDataNamespace) && mDataChannel != null) {
            try {
                Cast.CastApi.setMessageReceivedCallbacks(mApiClient, mDataNamespace, mDataChannel);
            } catch (IOException | IllegalStateException e) {
                LOGE(TAG, "reattachDataChannel()", e);
            }
        }
    }
```
on this line `Cast.CastApi.setMessageReceivedCallbacks(mApiClient, mDataNamespace, mDataChannel);`

Thanks.

**Comment by mntgoat** [comment]
Forgot to add the version, the manifest says version 2.6

**Comment by naddaf** [comment]
I can't see how that can happen. Are you getting a bunch of those?

**Comment by mntgoat** [comment]
I don't think it is too many, if I remember right it was something like 100 users total. I found another similar one while trying to find this one again. Both of these seem to be crashing deeper on the cast sdk code.  

Fatal Exception: java.lang.NullPointerException
       at com.google.android.gms.cast.Cast$CastApi$zza.setMessageReceivedCallbacks(Unknown Source)
       at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.reattachDataChannel(VideoCastManager.java:1958)
       at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.onConnectivityRecovered(VideoCastManager.java:932)
       at com.google.android.libraries.cast.companionlibrary.cast.BaseCastManager.onConnected(BaseCastManager.java:917)
       at com.google.android.gms.common.internal.zzk.zzk(Unknown Source)
       at com.google.android.gms.internal.zzmg.zzi(Unknown Source)
       at com.google.android.gms.internal.zzme.zzpi(Unknown Source)
       at com.google.android.gms.internal.zzme.onConnected(Unknown Source)
       at com.google.android.gms.internal.zzmi.onConnected(Unknown Source)
       at com.google.android.gms.internal.zzlz.onConnected(Unknown Source)
       at com.google.android.gms.common.internal.zzj$zzg.zzqv(Unknown Source)
       at com.google.android.gms.common.internal.zzj$zza.zzc(Unknown Source)
       at com.google.android.gms.common.internal.zzj$zza.zzv(Unknown Source)
       at com.google.android.gms.common.internal.zzj$zzc.zzqx(Unknown Source)
       at com.google.android.gms.common.internal.zzj$zzb.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5602)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by naddaf** [comment]
You might want to open a ticket on our SDK Issue Tracker so we can
investigate that inside the SDK itself.
