### ISSUE TITLE
Not found bitmap. or broken file

### ISSUE THREAD

**Issue by akkie2010** [googlecast/CastCompanionLibrary-android#267]
Fatal Exception: java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:299)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
       at java.util.concurrent.FutureTask.run(FutureTask.java:239)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:856)
Caused by java.lang.NullPointerException
       at com.google.android.libraries.cast.companionlibrary.utils.FetchBitmapTask.scaleBitmap(FetchBitmapTask.java:1129)
       at com.google.android.libraries.cast.companionlibrary.utils.FetchBitmapTask.doInBackground(FetchBitmapTask.java:39)
       at android.os.AsyncTask$2.call(AsyncTask.java:287)
       at java.util.concurrent.FutureTask.run(FutureTask.java:234)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:856)

**Comment by naddaf** [comment]
Need reproduction steps, some context, some more info....

**Comment by akkie2010** [comment]
Sorry, I don't use CastVideos-android.
It may be nothing.
because of "404 error".
