### ISSUE TITLE
Nullpointer expection upon VideoCastManager.getInstance().disconnect()

### ISSUE THREAD

**Issue by tobybonhof** [googlecast/CastCompanionLibrary-android#271]
```
17331-17331/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: nl.eredivisie, PID: 17331
                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.support.v4.media.MediaMetadataCompat.getMediaMetadata()' on a null object reference
                                                       at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplApi21.setMetadata(MediaSessionCompat.java:1982)
                                                       at android.support.v4.media.session.MediaSessionCompat.setMetadata(MediaSessionCompat.java:342)
                                                       at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.clearMediaSession(VideoCastManager.java:2480)
                                                       at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.onDisconnected(VideoCastManager.java:2600)
                                                       at com.google.android.libraries.cast.companionlibrary.cast.BaseCastManager.disconnectDevice(BaseCastManager.java:325)
                                                       at com.google.android.libraries.cast.companionlibrary.cast.BaseCastManager.disconnect(BaseCastManager.java:538)
                                                       at nl.xxx.cast.dialog.CastDialog$1.onClick(CastDialog.java:86)
                                                       at android.view.View.performClick(View.java:4786)
                                                       at android.view.View$PerformClick.run(View.java:19897)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5300)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

**Comment by tobybonhof** [comment]
basicly it crashes everytime when clearMediaSession gets called

**Comment by tobybonhof** [comment]
Turns out i needed to update the usage of the support library v4 to 23.1.1

    compile 'com.android.support:support-v4:23.1.1'
