### ISSUE TITLE
NullPointerException in IntroductoryOverlay

### ISSUE THREAD

**Issue by adrianrdzv** [googlecast/CastCompanionLibrary-android#292]
I'm getting the following crash sometimes after clicking close in the overlay: (CCL 2.8.3)

`E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.player.beta, PID: 19867
                                                                        java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
                                                                            at android.preference.PreferenceManager.getDefaultSharedPreferencesName(PreferenceManager.java:376)
                                                                            at android.preference.PreferenceManager.getDefaultSharedPreferences(PreferenceManager.java:371)
                                                                            at com.google.android.libraries.cast.companionlibrary.widgets.IntroductoryOverlay.setFtuShown(IntroductoryOverlay.java:259)
                                                                            at com.google.android.libraries.cast.companionlibrary.widgets.IntroductoryOverlay.access$1000(IntroductoryOverlay.java:79)
                                                                            at com.google.android.libraries.cast.companionlibrary.widgets.IntroductoryOverlay$2.onAnimationEnd(IntroductoryOverlay.java:246)
                                                                            at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1239)
                                                                            at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:766)
                                                                            at android.animation.ValueAnimator$AnimationHandler$1.run(ValueAnimator.java:801)
                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
                                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:695)
                                                                            at android.view.Choreographer.doFrame(Choreographer.java:628)
                                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:158)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

**Comment by naddaf** [comment]
Make sure that when you are leaving your app/activity or rotating your screen (configuration change), you don't attempt to show overlay, or if shown, try to remove that, etc. If you can reproduce that in CastVideos-android, please open this ticket again with reproduction steps. The line that the error points to is
SharedPreferences sharedPref = PreferenceManager.getDefaultSharedPreferences(ctx);
and there is nothing wrong about that line unless your context is not available anymore, etc.
