### ISSUE TITLE
Various Crashes

### ISSUE THREAD

**Issue by xtools-at** [googlecast/CastCompanionLibrary-android#295]
Hi,

I'm using CCL 2.8.3 in my app and received some crash reports, just wanted to give you the Stack Traces for further investigation:

```
Package: at.xtools.castcontroller.android
Version Code: 5
Version Name: 1.1
Android: 4.4.2
Android Build: KOT49H.I605VRUFND7
Manufacturer: samsung
Model: SCH-I605
Thread: main-1

java.lang.IllegalStateException: Can't copy a recycled bitmap
	at android.graphics.Bitmap.checkRecycled(Bitmap.java:390)
	at android.graphics.Bitmap.copy(Bitmap.java:669)
	at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplBase.cloneMetadataIfNeeded(MediaSessionCompat.java:1296)
	at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplBase.setMetadata(MediaSessionCompat.java:1311)
	at android.support.v4.media.session.MediaSessionCompat.setMetadata(MediaSessionCompat.java:404)
	at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.updateMediaSessionMetadata(VideoCastManager.java:2434)
	at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.onRemoteMediaPlayerMetadataUpdated(VideoCastManager.java:2178)
	at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager$24.onMetadataUpdated(VideoCastManager.java:1833)
	at com.google.android.gms.cast.RemoteMediaPlayer.onMetadataUpdated(Unknown Source)
	at com.google.android.gms.cast.RemoteMediaPlayer.zzb(Unknown Source)
	at com.google.android.gms.cast.RemoteMediaPlayer$1.onMetadataUpdated(Unknown Source)
	at com.google.android.gms.cast.internal.zzm.zza(Unknown Source)
	at com.google.android.gms.cast.internal.zzm.zzcf(Unknown Source)
	at com.google.android.gms.cast.RemoteMediaPlayer.onMessageReceived(Unknown Source)
	at com.google.android.gms.cast.internal.zze$zzb$4.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5602)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at dalvik.system.NativeStart.main(Native Method)
```

```
Package: at.xtools.castcontroller.android
Version Code: 5
Version Name: 1.1
Android: 6.0.1
Android Build: MMB29K.G935FXXU1APC8
Manufacturer: samsung
Model: SM-G935F
Thread: main-1

java.lang.RuntimeException: Unable to start activity ComponentInfo{at.xtools.castcontroller.android/com.google.android.libraries.cast.companionlibrary.cast.player.VideoCastControllerActivity}: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3253)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
	at android.app.ActivityThread.access$1100(ActivityThread.java:221)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7224)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
	at android.support.v7.app.AppCompatDelegateImplV7.setSupportActionBar(AppCompatDelegateImplV7.java:197)
	at android.support.v7.app.AppCompatActivity.setSupportActionBar(AppCompatActivity.java:126)
	at com.google.android.libraries.cast.companionlibrary.cast.player.VideoCastControllerActivity.setUpActionBar(VideoCastControllerActivity.java:293)
	at com.google.android.libraries.cast.companionlibrary.cast.player.VideoCastControllerActivity.onCreate(VideoCastControllerActivity.java:121)
	at android.app.Activity.performCreate(Activity.java:6876)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206)
	... 9 more
```

Regards,
Martin

**Comment by naddaf** [comment]
Thanks for reporting Martin. Regarding your second one, you need to make sure you use a a them for the VideoCastControllerActivity (in your manifest) that doesn't have an action bar, see the CastVideos-android sample, for example). As for your first one, can you reproduce that in the CastVideos-android sample?

**Comment by xtools-at** [comment]
Hi naddaf, thanks for your feedback!
I'll try your suggestions regarding No.2! Unfortunately I can't reproduce No.1 since these Crash Reports were generated automatically via HockeyApp by unknown users, and I don't know the steps they've taken :(

**Comment by naddaf** [comment]
For 1, are you seeing a lot of that? Are you seeing that on only that type of device? I haven't seen that before so I am not sure what is happening there.

**Comment by xtools-at** [comment]
no it came up one single time, but I don't have that many users using Google Cast, most are on FireTV/Fling. I'll keep you updated if it happens again!

**Comment by TommyVisic** [comment]
I'm seeing the same exception but with a different stack trace. Not sure if this is the same issue but here are details:

 Happens on an S5 running 4.4.2 if castManager.loadMedia(...) is called while the receiver app is currently playing (because loadMedia was previously callled), and only happens if the VideoCastManager was initialized with enabledLockScreen = true. Exception occurs a short while after the second loadMedia call is made when there's an internal state change in VideoCastManager.

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.tastemade.player, PID: 22747
                  java.lang.IllegalStateException: Can't copy a recycled bitmap
                      at android.graphics.Bitmap.checkRecycled(Bitmap.java:390)
                      at android.graphics.Bitmap.copy(Bitmap.java:669)
                      at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplBase.cloneMetadataIfNeeded(MediaSessionCompat.java:1296)
                      at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplBase.setMetadata(MediaSessionCompat.java:1311)
                      at android.support.v4.media.session.MediaSessionCompat.setMetadata(MediaSessionCompat.java:404)
                      at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.updateMediaSessionMetadata(VideoCastManager.java:2434)
                      at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.setUpMediaSession(VideoCastManager.java:2266)
                      at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.updateMediaSession(VideoCastManager.java:2372)
                      at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.onRemoteMediaPlayerStatusUpdated(VideoCastManager.java:2071)
                      at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.access$200(VideoCastManager.java:130)
                      at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager$22.onStatusUpdated(VideoCastManager.java:1810)
                      at com.google.android.gms.cast.RemoteMediaPlayer.onStatusUpdated(Unknown Source)
                      at com.google.android.gms.cast.RemoteMediaPlayer.zza(Unknown Source)
                      at com.google.android.gms.cast.RemoteMediaPlayer$1.onStatusUpdated(Unknown Source)
                      at com.google.android.gms.cast.internal.zzm.zza(Unknown Source)
                      at com.google.android.gms.cast.internal.zzm.zzcf(Unknown Source)
                      at com.google.android.gms.cast.RemoteMediaPlayer.onMessageReceived(Unknown Source)
                      at com.google.android.gms.cast.internal.zze$zzb$4.run(Unknown Source)
                      at android.os.Handler.handleCallback(Handler.java:733)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:136)
                      at android.app.ActivityThread.main(ActivityThread.java:5586)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
```

Possibly related is that the cast dialog looks like this when enableLockScreen() is used during initialize
![image](https://cloud.githubusercontent.com/assets/3027722/15028367/31d90ea2-120e-11e6-974b-0ee19e65da7d.png)

And like this when enableLockScreen() is not used during initialize

![image](https://cloud.githubusercontent.com/assets/3027722/15028474/b7e7c3da-120e-11e6-9597-7f87404b2b62.png)

**Comment by naddaf** [comment]
I cannot reproduce these and I suspect Samsung is doing something strange in their builds and since i don't know what they do, I cannot address them.

**Comment by Zspecial** [comment]
I have No idea what any of this means. If this has anything to do with my
phone personally please translate this for me. Thinking I would learn from
just reading the information on the websites definitely does not work to my
benefit. Sorry to have bothered you.
Please unsubscribe me from your newsletter.
Thank you

💞§¤ Coi-P90Percy-Tayz ¤§💞

**Comment by rini-m** [comment]
Hi,
I am having same issue.

Crash log -
Fatal Exception: java.lang.IllegalStateException: Can't copy a recycled bitmap
       at android.graphics.Bitmap.checkRecycled(Bitmap.java:390)
       at android.graphics.Bitmap.copy(Bitmap.java:669)
       at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplBase.cloneMetadataIfNeeded(MediaSessionCompat.java:1436)
       at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplBase.setMetadata(MediaSessionCompat.java:1450)
       at android.support.v4.media.session.MediaSessionCompat.setMetadata(MediaSessionCompat.java:419)
       at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.updateMediaSessionMetadata(VideoCastManager.java:2453)
       at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.setUpMediaSession(VideoCastManager.java:2285)
       at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.updateMediaSession(VideoCastManager.java:2391)
       at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.onRemoteMediaPlayerStatusUpdated(VideoCastManager.java:2090)
       at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.access$200(VideoCastManager.java:130)
       at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager$22.onStatusUpdated(VideoCastManager.java:1829)
       at com.google.android.gms.cast.RemoteMediaPlayer.onStatusUpdated(Unknown Source)
       at com.google.android.gms.cast.RemoteMediaPlayer.zza(Unknown Source)
       at com.google.android.gms.cast.RemoteMediaPlayer$1.onStatusUpdated(Unknown Source)
       at com.google.android.gms.cast.internal.zzm.zza(Unknown Source)
       at com.google.android.gms.cast.internal.zzm.zzcf(Unknown Source)
       at com.google.android.gms.cast.RemoteMediaPlayer.onMessageReceived(Unknown Source)
       at com.google.android.gms.cast.internal.zze$zzb$4.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5593)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)

Crash scenario - I have a screen with tv shows and movies list. While a movie is being casted to receiver, if I navigate back from CastControllerActivity and try to cast tv show, CastControllerActivity launches and then it crash.

**Comment by naddaf** [comment]
@rini-m Can you reproduce this with CastVideos-android app so I can follow the steps and see if that issue is in CCL or elswhere?

**Comment by naddaf** [comment]
Cannot reproduce.

**Comment by styrken** [comment]
I have the exact same issue on a Samsung 4.4.2.

```
06-16 11:28:15.881 5640-5640/com.stofa.webtv E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: com.stofa.webtv, PID: 5640
                                                               java.lang.IllegalStateException: Can't copy a recycled bitmap
                                                                   at android.graphics.Bitmap.checkRecycled(Bitmap.java:390)
                                                                   at android.graphics.Bitmap.copy(Bitmap.java:669)
                                                                   at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplBase.cloneMetadataIfNeeded(MediaSessionCompat.java:1296)
                                                                   at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplBase.setMetadata(MediaSessionCompat.java:1311)
                                                                   at android.support.v4.media.session.MediaSessionCompat.setMetadata(MediaSessionCompat.java:404)
                                                                   at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.updateMediaSessionMetadata(VideoCastManager.java:2434)
                                                                   at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.setUpMediaSession(VideoCastManager.java:2266)
                                                                   at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.updateMediaSession(VideoCastManager.java:2372)
                                                                   at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.onRemoteMediaPlayerStatusUpdated(VideoCastManager.java:2071)
                                                                   at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.access$200(VideoCastManager.java:130)
                                                                   at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager$22.onStatusUpdated(VideoCastManager.java:1810)
                                                                   at com.google.android.gms.cast.RemoteMediaPlayer.onStatusUpdated(Unknown Source)
                                                                   at com.google.android.gms.cast.RemoteMediaPlayer.zza(Unknown Source)
                                                                   at com.google.android.gms.cast.RemoteMediaPlayer$1.onStatusUpdated(Unknown Source)
                                                                   at com.google.android.gms.cast.internal.zzm.zza(Unknown Source)
                                                                   at com.google.android.gms.cast.internal.zzm.zzcf(Unknown Source)
                                                                   at com.google.android.gms.cast.RemoteMediaPlayer.onMessageReceived(Unknown Source)
                                                                   at com.google.android.gms.cast.internal.zze$zzb$4.run(Unknown Source)
                                                                   at android.os.Handler.handleCallback(Handler.java:733)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at android.os.Looper.loop(Looper.java:136)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5579)
                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:515)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
                                                                   at dalvik.system.NativeStart.main(Native Method)
```

**Comment by emilianogonzalezar** [comment]
Hey,

Using CCL version 2.6.1 (commit 2cd84abb59c3383ce26dca0a09ead6a7a432efb0) I was able to reproduce this error, with a particular device (ACER B1-A71 tablet).

`07-12 15:26:26.985 6059-6059/com.arsat.odeon E/AndroidRuntime: FATAL EXCEPTION: main
                                                               java.lang.IllegalStateException: Can't copy a recycled bitmap
                                                                   at android.graphics.Bitmap.checkRecycled(Bitmap.java:239)
                                                                   at android.graphics.Bitmap.copy(Bitmap.java:428)
                                                                   at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplBase.cloneMetadataIfNeeded(MediaSessionCompat.java:1436)
                                                                   at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplBase.setMetadata(MediaSessionCompat.java:1450)
                                                                   at android.support.v4.media.session.MediaSessionCompat.setMetadata(MediaSessionCompat.java:419)
                                                                   at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.updateMediaSessionMetadata(VideoCastManager.java:2415)
                                                                   at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.setUpMediaSession(VideoCastManager.java:2249)
                                                                   at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.updateMediaSession(VideoCastManager.java:2354)
                                                                   at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.onRemoteMediaPlayerStatusUpdated(VideoCastManager.java:2058)
                                                                   at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.access$200(VideoCastManager.java:140)
                                                                   at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager$22.onStatusUpdated(VideoCastManager.java:1795)
                                                                   at com.google.android.gms.cast.RemoteMediaPlayer.onStatusUpdated(Unknown Source)
                                                                   at com.google.android.gms.cast.RemoteMediaPlayer.zza(Unknown Source)
                                                                   at com.google.android.gms.cast.RemoteMediaPlayer$1.onStatusUpdated(Unknown Source)
                                                                   at com.google.android.gms.cast.internal.zzm.zza(Unknown Source)
                                                                   at com.google.android.gms.cast.internal.zzm.zzbZ(Unknown Source)
                                                                   at com.google.android.gms.cast.RemoteMediaPlayer.onMessageReceived(Unknown Source)
                                                                   at com.google.android.gms.cast.internal.zze$zzb$4.run(Unknown Source)
                                                                   at android.os.Handler.handleCallback(Handler.java:615)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                   at android.os.Looper.loop(Looper.java:153)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:4987)
                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:511)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
                                                                   at dalvik.system.NativeStart.main(Native Method)`


I fixed it changing the updateMediaSessionMetadata method from this:


    private void updateMediaSessionMetadata() {
        if ((mMediaSessionCompat == null) || !isFeatureEnabled(FEATURE_LOCKSCREEN)) {
            return;
        }

        try {
            MediaInfo info = getRemoteMediaInformation();
            if (info == null) {
                return;
            }
            final MediaMetadata mm = info.getMetadata();
            MediaMetadataCompat currentMetadata = mMediaSessionCompat.getController().getMetadata();
            MediaMetadataCompat.Builder newBuilder = currentMetadata == null
                    ? new MediaMetadataCompat.Builder()
                    : new MediaMetadataCompat.Builder(currentMetadata);
            MediaMetadataCompat metadata = newBuilder
                    // used in lock screen for pre-lollipop
                    .putString(MediaMetadataCompat.METADATA_KEY_TITLE,
                            mm.getString(MediaMetadata.KEY_TITLE))
                    // used in lock screen for pre-lollipop
                    .putString(MediaMetadataCompat.METADATA_KEY_ALBUM_ARTIST,
                            mContext.getResources().getString(
                                    R.string.ccl_casting_to_device, getDeviceName()))
                    // used in MediaRouteController dialog
                    .putString(MediaMetadataCompat.METADATA_KEY_DISPLAY_TITLE,
                            mm.getString(MediaMetadata.KEY_TITLE))
                    // used in MediaRouteController dialog
                    .putString(MediaMetadataCompat.METADATA_KEY_DISPLAY_SUBTITLE,
                            mm.getString(MediaMetadata.KEY_SUBTITLE))
                    .putLong(MediaMetadataCompat.METADATA_KEY_DURATION,
                            info.getStreamDuration())
                    .build();
            mMediaSessionCompat.setMetadata(metadata);

            Uri iconUri = mm.hasImages() ? mm.getImages().get(0).getUrl() : null;
            if (iconUri == null) {
                Bitmap bm = BitmapFactory.decodeResource(
                        mContext.getResources(), R.drawable.album_art_placeholder);
                mMediaSessionCompat.setMetadata(newBuilder
                        .putBitmap(MediaMetadataCompat.METADATA_KEY_DISPLAY_ICON, bm)
                        .build());
            } else {
                if (mMediaSessionIconFetchTask != null) {
                    mMediaSessionIconFetchTask.cancel(true);
                }
                mMediaSessionIconFetchTask = new FetchBitmapTask() {
                    @Override
                    protected void onPostExecute(Bitmap bitmap) {
                        if (mMediaSessionCompat != null) {
                            MediaMetadataCompat currentMetadata = mMediaSessionCompat
                                    .getController().getMetadata();
                            MediaMetadataCompat.Builder newBuilder = currentMetadata == null
                                    ? new MediaMetadataCompat.Builder()
                                    : new MediaMetadataCompat.Builder(currentMetadata);
                            mMediaSessionCompat.setMetadata(newBuilder.putBitmap(
                                    MediaMetadataCompat.METADATA_KEY_DISPLAY_ICON, bitmap).build());
                        }
                        mMediaSessionIconFetchTask = null;
                    }
                };
                mMediaSessionIconFetchTask.execute(iconUri);
            }

        } catch (NotFoundException e) {
            LOGE(TAG, "Failed to update Media Session due to resource not found", e);
        } catch (TransientNetworkDisconnectionException | NoConnectionException e) {
            LOGE(TAG, "Failed to update Media Session due to network issues", e);
        }
    }

to this:

    private void updateMediaSessionMetadata() {
        if ((mMediaSessionCompat == null) || !isFeatureEnabled(FEATURE_LOCKSCREEN)) {
            return;
        }

        try {
            MediaInfo info = getRemoteMediaInformation();
            if (info == null) {
                return;
            }
            final MediaMetadata mm = info.getMetadata();
            MediaMetadataCompat currentMetadata = mMediaSessionCompat.getController().getMetadata();
            MediaMetadataCompat.Builder newBuilder = currentMetadata == null
                    ? new MediaMetadataCompat.Builder()
                    : new MediaMetadataCompat.Builder(currentMetadata);
            MediaMetadataCompat.Builder builder = newBuilder
                    // used in lock screen for pre-lollipop
                    .putString(MediaMetadataCompat.METADATA_KEY_TITLE,
                            mm.getString(MediaMetadata.KEY_TITLE))
                    // used in lock screen for pre-lollipop
                    .putString(MediaMetadataCompat.METADATA_KEY_ALBUM_ARTIST,
                            mContext.getResources().getString(
                                    R.string.ccl_casting_to_device, getDeviceName()))
                    // used in MediaRouteController dialog
                    .putString(MediaMetadataCompat.METADATA_KEY_DISPLAY_TITLE,
                            mm.getString(MediaMetadata.KEY_TITLE))
                    // used in MediaRouteController dialog
                    .putString(MediaMetadataCompat.METADATA_KEY_DISPLAY_SUBTITLE,
                            mm.getString(MediaMetadata.KEY_SUBTITLE))
                    .putLong(MediaMetadataCompat.METADATA_KEY_DURATION,
                            info.getStreamDuration());

            Uri iconUri = mm.hasImages() ? mm.getImages().get(0).getUrl() : null;
            if (iconUri == null) {
                Bitmap bm = BitmapFactory.decodeResource(
                        mContext.getResources(), R.drawable.album_art_placeholder);
                newBuilder.putBitmap(MediaMetadataCompat.METADATA_KEY_DISPLAY_ICON, bm);
            }

            mMediaSessionCompat.setMetadata(builder.build());

            if (iconUri != null) {
                if (mMediaSessionIconFetchTask != null) {
                    mMediaSessionIconFetchTask.cancel(true);
                }
                mMediaSessionIconFetchTask = new FetchBitmapTask() {
                    @Override
                    protected void onPostExecute(Bitmap bitmap) {
                        if (mMediaSessionCompat != null) {
                            MediaMetadataCompat currentMetadata = mMediaSessionCompat
                                    .getController().getMetadata();
                            MediaMetadataCompat.Builder newBuilder = currentMetadata == null
                                    ? new MediaMetadataCompat.Builder()
                                    : new MediaMetadataCompat.Builder(currentMetadata);
                            mMediaSessionCompat.setMetadata(newBuilder.putBitmap(
                                    MediaMetadataCompat.METADATA_KEY_DISPLAY_ICON, bitmap).build());
                        }
                        mMediaSessionIconFetchTask = null;
                    }
                };
                mMediaSessionIconFetchTask.execute(iconUri);
            }

        } catch (NotFoundException e) {
            LOGE(TAG, "Failed to update Media Session due to resource not found", e);
        } catch (TransientNetworkDisconnectionException | NoConnectionException e) {
            LOGE(TAG, "Failed to update Media Session due to network issues", e);
        }
    }

**Comment by naddaf** [comment]
@emilianogonzalezar In your reproducible scenario, is it the case the case that there is no image associated with that media item?

**Comment by emilianogonzalezar** [comment]
@naddaf yes it is.

**Comment by Gi0rgi0s** [comment]
@naddaf Any updates on this issue?

I'm also noticing the issue on LG G2 (4.4.2) and Samsung Galaxy Tab Pro T520 (4.4.2).

It happens when I cast a video, then switch to a video that is not available on the server. It could be caused by the lack of metadata.

    Fatal Exception: java.lang.IllegalStateException: Can't copy a recycled bitmap
        at android.graphics.Bitmap.checkRecycled(Bitmap.java:345)
        at android.graphics.Bitmap.copy(Bitmap.java:554)
        at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplBase.cloneMetadataIfNeeded(MediaSessionCompat.java:1296)
        at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplBase.setMetadata(MediaSessionCompat.java:1311)
        at android.support.v4.media.session.MediaSessionCompat.setMetadata(MediaSessionCompat.java:404)
        at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.updateMediaSessionMetadata(VideoCastManager.java:2387)
        at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.onRemoteMediaPlayerMetadataUpdated(VideoCastManager.java:2131)
        at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager$24.onMetadataUpdated(VideoCastManager.java:1819)
        at com.google.android.gms.cast.RemoteMediaPlayer.onMetadataUpdated(Unknown Source)
        at com.google.android.gms.cast.RemoteMediaPlayer.zzb(Unknown Source)
        at com.google.android.gms.cast.RemoteMediaPlayer$1.onMetadataUpdated(Unknown Source)
        at com.google.android.gms.cast.internal.zzm.zza(Unknown Source)
        at com.google.android.gms.cast.internal.zzm.zzbZ(Unknown Source)
        at com.google.android.gms.cast.RemoteMediaPlayer.onMessageReceived(Unknown Source)
        at com.google.android.gms.cast.internal.zze$zzb$4.run(Unknown Source)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5105)
        at java.lang.reflect.Method.invokeNative(Method.java)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
        at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by xtools-at** [comment]
**I think I've found a solution for the crash reported in the first post/OP:**

I didn't add any Images to my MediaMetadata-Object, which I added to my MediaInfo and threw at VideoCastManager (simply because there was no point in it in my use case).
At some Event, android.support.v4.media.session.MediaSessionCompat tries to clone the Metadata and crashes when attemting to duplicate the (not available) Image - it's the Support Library's fault...

I've added some generic Icon to my Metadata and implemented it like in Universal Musicplayer:
```
            // Create Metadata
            MediaMetadata mediaMetadata = new MediaMetadata(MediaMetadata.MEDIA_TYPE_MOVIE);
            mediaMetadata.putString(MediaMetadata.KEY_TITLE, "foo");
            mediaMetadata.putString(MediaMetadata.KEY_SUBTITLE, "bar");

            //! Add Image to Metadata to prevent CCL crash
            WebImage image = new WebImage(Uri.parse("http://www.example.com/icon.png"));
            // Add twice for CCL - See https://github.com/googlesamples/android-UniversalMusicPlayer/blob/master/mobile/src/main/java/com/example/android/uamp/playback/CastPlayback.java
            mediaMetadata.addImage(image);
            mediaMetadata.addImage(image);

            // Create MediaInfo
            MediaInfo mediaInfo = new MediaInfo.Builder(videoUrl)
                    .setStreamDuration(43200000L)
                    .setMetadata(mediaMetadata)
                    .setContentType("video/mp4")
                    .setStreamType(MediaInfo.STREAM_TYPE_BUFFERED);
                    .build();

            // Start casting
            mVideoCastManager.loadMedia(mediaInfo, true, 0);
```

**Comment by daedamr** [comment]
This happens to me on 2.8.2 when no image is attached to cast metadata:

```
bundleMetadata.putStringArrayList(KidsConstants.CAST_IMAGES, null);
```

Crashlog:
```
java.lang.IllegalStateException: Can't copy a recycled bitmap
                                                                       at android.graphics.Bitmap.checkRecycled(Bitmap.java:390)
                                                                       at android.graphics.Bitmap.copy(Bitmap.java:669)
                                                                       at android.support.v4.media.MediaMetadataCompat$Builder.<init>(MediaMetadataCompat.java:668)
                                                                       at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplBase.setMetadata(MediaSessionCompat.java:1523)
                                                                       at android.support.v4.media.session.MediaSessionCompat.setMetadata(MediaSessionCompat.java:432)
                                                                       at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.updateMediaSessionMetadata(VideoCastManager.java:2434)
                                                                       at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.setUpMediaSession(VideoCastManager.java:2266)
                                                                       at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.updateMediaSession(VideoCastManager.java:2372)
                                                                       at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.onRemoteMediaPlayerStatusUpdated(VideoCastManager.java:2071)
                                                                       at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.access$200(VideoCastManager.java:130)
                                                                       at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager$22.onStatusUpdated(VideoCastManager.java:1810)
                                                                       at com.google.android.gms.cast.RemoteMediaPlayer.onStatusUpdated(Unknown Source)
                                                                       at com.google.android.gms.cast.RemoteMediaPlayer.zza(Unknown Source)
                                                                       at com.google.android.gms.cast.RemoteMediaPlayer$1.onStatusUpdated(Unknown Source)
                                                                       at com.google.android.gms.cast.internal.zzn.onStatusUpdated(Unknown Source)
                                                                       at com.google.android.gms.cast.internal.zzn.zza(Unknown Source)
                                                                       at com.google.android.gms.cast.internal.zzn.zzgt(Unknown Source)
                                                                       at com.google.android.gms.cast.RemoteMediaPlayer.onMessageReceived(Unknown Source)
                                                                       at com.google.android.gms.cast.internal.zze$zzb$4.run(Unknown Source)
                                                                       at android.os.Handler.handleCallback(Handler.java:733)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:146)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5602)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
                                                                       at dalvik.system.NativeStart.main(Native Method)
```
