### ISSUE TITLE
android.view.InflateException: Binary XML file line #7: Error inflating class com.google.android.libraries.cast.companionlibrary.widgets.MiniController

### ISSUE THREAD

**Issue by dhtml** [googlecast/CastCompanionLibrary-android#314]
Everything works well on my device and all devices i tested on, but on some certain devices this happens:

```

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ibakatv.mobile/com.ibakatv.mobile.MyScreens.MovieActivity}: android.view.InflateException: Binary XML file line #7: Error inflating class com.google.android.libraries.cast.companionlibrary.widgets.MiniController
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2380)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2432)
at android.app.ActivityThread.access$800(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1342)
at android.os.Handler.dispatchMessage(Handler.java:110)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:5336)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
at dalvik.system.NativeStart.main(Native Method)
Caused by: android.view.InflateException: Binary XML file line #7: Error inflating class com.google.android.libraries.cast.companionlibrary.widgets.MiniController
at android.view.LayoutInflater.createView(LayoutInflater.java:620)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276)
at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:136)
at com.ibakatv.mobile.MyScreens.MovieActivity.onCreate(MovieActivity.java:248)
at android.app.Activity.performCreate(Activity.java:5358)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2334)
... 11 more
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Constructor.constructNative(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at android.view.LayoutInflater.createView(LayoutInflater.java:594)
... 22 more
Caused by: java.lang.IllegalStateException: No VideoCastManager instance was found, did you forget to initialize it?
at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.getInstance(VideoCastManager.java:270)
at com.google.android.libraries.cast.companionlibrary.widgets.MiniController.(MiniController.java:111)
... 25 more


************ DEVICE INFORMATION ***********
Time: 27-May-2016 09:58
Brand: Infinix
Device: Infinix_X507
Model: Infinix X507
Id: KOT49H
Product: Infinix_X507

************ FIRMWARE ************
SDK: 19
Release: 4.4.2
```

**Comment by naddaf** [comment]
The line here:
Caused by: java.lang.IllegalStateException: No VideoCastManager instance was found, did you forget to initialize it?
points to the library not being initialized. Initialization of the library is the responsibility of the app so if it is not happening on a certain device, you need to trouble shoot that on your end.

**Comment by dhtml** [comment]
Thanks, figured it out
