### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.common.api.Api$zzb 

### ISSUE THREAD

**Issue by mntgoat** [googlecast/CastCompanionLibrary-android#319]
I've received on crashlytics 1218 crash reports from 1027 users with this stack trace below. I think the issue is probably outside of the cast companion library and on the actual SDK but I wanted to confirm before opening an issue there. Thanks. 

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.common.api.Api$zzb com.google.android.gms.common.api.GoogleApiClient.zza(com.google.android.gms.common.api.Api$zzc)' on a null object reference
       at com.google.android.gms.cast.Cast$CastApi$zza.setMessageReceivedCallbacks(Unknown Source)
       at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.reattachDataChannel(VideoCastManager.java:1976)
       at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.onConnectivityRecovered(VideoCastManager.java:931)
       at com.google.android.libraries.cast.companionlibrary.cast.BaseCastManager.onConnected(BaseCastManager.java:899)
       at com.google.android.gms.common.internal.zzk.zzk(Unknown Source)
       at com.google.android.gms.common.api.internal.zzj.zzi(Unknown Source)
       at com.google.android.gms.common.api.internal.zzh.zzpx(Unknown Source)
       at com.google.android.gms.common.api.internal.zzh.onConnected(Unknown Source)
       at com.google.android.gms.common.api.internal.zzl.onConnected(Unknown Source)
       at com.google.android.gms.common.api.internal.zzc.onConnected(Unknown Source)
       at com.google.android.gms.common.internal.zzj$zzg.zzqL(Unknown Source)
       at com.google.android.gms.common.internal.zzj$zza.zzc(Unknown Source)
       at com.google.android.gms.common.internal.zzj$zza.zzw(Unknown Source)
       at com.google.android.gms.common.internal.zzj$zzc.zzqN(Unknown Source)
       at com.google.android.gms.common.internal.zzj$zzb.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7229)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by naddaf** [comment]
Doesn't seem to be CCL related.
