### ISSUE TITLE
NPE caused by source.getConfig() in Utils.scaleAndCenterCropBitmap(Bitmap, int, int)

### ISSUE THREAD

**Issue by DavidEdwards** [googlecast/CastCompanionLibrary-android#322]
Looks to be an NPE in [Utils.scaleAndCenterCropBitmap(Bitmap, int, int)](https://github.com/googlecast/CastCompanionLibrary-android/blob/master/src/com/google/android/libraries/cast/companionlibrary/utils/Utils.java#L369). 

The `Bitmap.Config` acquired from `source.getConfig()` is null.

The exception is thrown in `Bitmap.createBitmap(DisplayMetrics, int, int, Config, boolean)` here:

`Bitmap bm = nativeCreate(null, 0, width, width, height, config.nativeInt, true);`

```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'int android.graphics.Bitmap$Config.nativeInt' on a null object reference
       at android.graphics.Bitmap.createBitmap(Bitmap.java:812)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:789)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:756)
       at com.google.android.libraries.cast.companionlibrary.utils.Utils.scaleAndCenterCropBitmap(SourceFile:369)
       at com.google.android.libraries.cast.companionlibrary.notification.VideoCastNotificationService$2.onPostExecute(SourceFile:1240)
       at android.os.AsyncTask.finish(AsyncTask.java:636)
       at android.os.AsyncTask.access$500(AsyncTask.java:177)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:211)
       at android.app.ActivityThread.main(ActivityThread.java:5373)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
```

**Comment by naddaf** [comment]
This is addressed in v2.9.0
