### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.common.api.Api$zze 

### ISSUE THREAD

**Issue by mntgoat** [googlecast/CastCompanionLibrary-android#323]
Getting this crash on crashlytics. Don't know how to reproduce. The SDK team said it is a CCL issue https://code.google.com/p/google-cast-sdk/issues/detail?id=871

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 
'com.google.android.gms.common.api.Api$zze com.google.android.gms.common.api.GoogleApiClient.zza(com.google.android.gms.common.api.Api$zzc)' on a null object reference
       at com.google.android.gms.cast.Cast$CastApi$zza.setMessageReceivedCallbacks(Unknown Source)
       at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.reattachDataChannel(VideoCastManager.java:1974)
       at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.onConnectivityRecovered(VideoCastManager.java:931)
       at com.google.android.libraries.cast.companionlibrary.cast.BaseCastManager.onConnected(BaseCastManager.java:901)
       at com.google.android.gms.common.internal.zzl.zzm(Unknown Source)
       at com.google.android.gms.internal.zzof.zzk(Unknown Source)
       at com.google.android.gms.internal.zzod.zzsb(Unknown Source)
       at com.google.android.gms.internal.zzod.onConnected(Unknown Source)
       at com.google.android.gms.internal.zzoh.onConnected(Unknown Source)
       at com.google.android.gms.internal.zznw.onConnected(Unknown Source)
       at com.google.android.gms.common.internal.zzk$1.onConnected(Unknown Source)
       at com.google.android.gms.common.internal.zzd$zzj.zztp(Unknown Source)
       at com.google.android.gms.common.internal.zzd$zza.zzc(Unknown Source)
       at com.google.android.gms.common.internal.zzd$zza.zzw(Unknown Source)
       at com.google.android.gms.common.internal.zzd$zze.zztr(Unknown Source)
       at com.google.android.gms.common.internal.zzd$zzd.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java)
       at android.os.Looper.loop(Looper.java)
       at android.app.ActivityThread.main(ActivityThread.java)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)

**Comment by naddaf** [comment]
Any pattern on: 
- how many of this do you see?
- Any particular type of device/ android version?
- What version of cast sdk?

**Comment by mntgoat** [comment]
On my latest update which has been out for less than a week this is my second most common crash with over 200 users affected. 

Seems to happen on 4,5,6 which is what my app targets (4+). Various manufacturers. 

I shipped this last version with Google Play Services 9.0.1 but it was happening before that as well. I'm using CCL 2.8.4

Thanks.

**Comment by naddaf** [comment]
Since CCL hasn't changed for a while, how come this is happening now? Any clue?

**Comment by mntgoat** [comment]
Is not new, at least not for me. I think it is the first time I submitted it to the SDK as an issue though.

https://github.com/googlecast/CastCompanionLibrary-android/issues/319
https://github.com/googlecast/CastCompanionLibrary-android/issues/255

**Comment by naddaf** [comment]
The reattachDataChannel is:
 ```java
    private void reattachMediaChannel() {
        if (mRemoteMediaPlayer != null && mApiClient != null) {
            try {
                LOGD(TAG, "Registering MediaChannel namespace");
                Cast.CastApi.setMessageReceivedCallbacks(mApiClient,
                        mRemoteMediaPlayer.getNamespace(), mRemoteMediaPlayer);
            } catch (IOException | IllegalStateException e) {
                LOGE(TAG, "reattachMediaChannel()", e);
            }
        }
    }
```
so mApiClient is not null when that is called. Let me reopen the internal issue against SDK to see what they come up with, I can't see anything wrong on CCL's side.

**Comment by mntgoat** [comment]
Thank you.

**Comment by vokrut** [comment]
I'm too getting error on last CCL. It's stable when click on MediaButton and then in dialog with cast devices "Cast to" click on device

08-05 11:21:01.147 3626-3626/app.rayscast.air E/AndroidRuntime: FATAL EXCEPTION: main
                                                                Process: app.rayscast.air, PID: 3626
                                                                java.lang.NoSuchMethodError: com.google.android.gms.common.internal.safeparcel.zza.zzaq
                                                                    at com.google.android.gms.cast.zzb.zzW(Unknown Source)
                                                                    at com.google.android.gms.cast.zzb.createFromParcel(Unknown Source)
                                                                    at android.os.Parcel.readParcelable(Parcel.java:2111)
                                                                    at android.os.Parcel.readValue(Parcel.java:2020)
                                                                    at android.os.Parcel.readArrayMapInternal(Parcel.java:2321)
                                                                    at android.os.Bundle.unparcel(Bundle.java:249)
                                                                    at android.os.Bundle.getParcelable(Bundle.java:1206)
                                                                    at com.google.android.gms.cast.CastDevice.getFromBundle(Unknown Source)
                                                                    at com.google.android.libraries.cast.companionlibrary.cast.CastMediaRouterCallback.onRouteSelected(CastMediaRouterCallback.java:56)
                                                                    at android.support.v7.media.MediaRouter$GlobalMediaRouter$CallbackHandler.invokeCallback(MediaRouter.java:2850)
                                                                    at android.support.v7.media.MediaRouter$GlobalMediaRouter$CallbackHandler.handleMessage(MediaRouter.java:2800)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                    at android.os.Looper.loop(Looper.java:193)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5333)
                                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:515)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
                                                                    at dalvik.system.NativeStart.main(Native Method)

**Comment by vokrut** [comment]
I've decided my problem when downgrade libraries in builde.gradle file from
    compile 'com.google.android.gms:play-services-drive:9.4.0'
    compile 'com.google.android.gms:play-services-ads:9.4.0'
to
    compile 'com.google.android.gms:play-services-drive:9.0.0'
    compile 'com.google.android.gms:play-services-ads:9.0.0'

**Comment by naddaf** [comment]
This is not a CCL issue; if anyone thinks otherwise, please let me know.

**Comment by sandipborad** [comment]
I am generating this type of issue

Attempt to invoke virtual method 'com.google.android.gms.common.api.PendingResult com.google.android.gms.cast.RemoteMediaPlayer.load(com.google.android.gms.common.api.GoogleApiClient, com.google.android.gms.cast.MediaInfo, boolean)' on a null object reference
