### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by dinhhieuac** [googlecast/CastCompanionLibrary-android#342]
Hi Dev
My app crash when played in a long time
 java.util.concurrent.RejectedExecutionException: Task android.os.AsyncTask$3@37e1033 rejected from java.util.concurrent.ThreadPoolExecutor@e9ff0[Running, pool size = 17, active threads = 17, queued tasks = 128, completed tasks = 394]
                                                                        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2014)
                                                                        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:794)
                                                                        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1340)
                                                                        at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:607)
                                                                        at com.google.android.libraries.cast.companionlibrary.utils.FetchBitmapTask.execute(FetchBitmapTask.java:144)
                                                                        at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.updateMediaSessionMetadata(VideoCastManager.java:2455)
                                                                        at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager.onRemoteMediaPlayerMetadataUpdated(VideoCastManager.java:2177)
                                                                        at com.google.android.libraries.cast.companionlibrary.cast.VideoCastManager$24.onMetadataUpdated(VideoCastManager.java:1833)
                                                                        at com.google.android.gms.cast.RemoteMediaPlayer.onMetadataUpdated(Unknown Source)
                                                                        at com.google.android.gms.cast.RemoteMediaPlayer.zzb(Unknown Source)
                                                                        at com.google.android.gms.cast.RemoteMediaPlayer$1.onMetadataUpdated(Unknown Source)
                                                                        at com.google.android.gms.cast.internal.zzm.onMetadataUpdated(Unknown Source)
                                                                        at com.google.android.gms.cast.internal.zzm.zza(Unknown Source)
                                                                        at com.google.android.gms.cast.internal.zzm.zzcC(Unknown Source)
                                                                        at com.google.android.gms.cast.RemoteMediaPlayer.onMessageReceived(Unknown Source)
                                                                        at com.google.android.gms.cast.internal.zze$zzb$4.run(Unknown Source)
                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:158)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by naddaf** [comment]
There seems to be a large number of queued tasks to fetch the bitmaps; you need to look at your media/receiver to see what is going on.
